language: objective-c
before_install:
- brew update
- brew unlink xctool
- brew install xctool
- rvm get stable
- rvm install 2.1.0
- rvm use 2.1.0
script: rake test:ci analyze
cache:
  bundler: true
  directories:
  - Pods
notifications:
  email: false
  hipchat:
    template:
    - ! '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    rooms:
      secure: HGqjX2eA46R+IkY4WBbDLRc/h87CuxQNHzzDSlUMtOTtHvbXSBJg+ualNulm5YxBNiXIxnnvXPwb5LBB4JYp0LwY79ZX9HZ8fu3oMwooXGnkZU0mPxYx4JEO96aDgIqUfshXPf+xzfBc6xLVkq7ieSsqDF7z9tkxPNLGKAS/H1U=
